apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: default
stringData:
  MONGODB_URI: "mongodb+srv://farhan091:farhan091@cluster0.6zb2hoi.mongodb.net/emi-platform?retryWrites=true&w=majority&appName=Cluster0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emi-app-deployment
  namespace: default
  labels:
    app: emi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emi-app
  template:
    metadata:
      labels:
        app: emi-app
    spec:
      containers:
      - name: emi-app
        image: farhan091/1fi-assignment-app:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: MONGODB_URI