apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-ingress-router
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  rules:
  - host: 1fi.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: emi-app-service
            port:
              number: 80
  - host: argocd-1fi.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            namespace: argocd
            port:
              number: 443
  - host: grafana-1fi.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-grafana
            namespace: monitoring
            port:
              number: 80